### ISSUE TITLE
ES module support

### ISSUE THREAD

**Issue by jorgebucaran** [jcubic/lips#125]
How would I go about using ES modules with LIPS? [ECMAScript modules](https://tc39.es/ecma262/#sec-modules) are the official standard format to package JavaScript code for reuse. It would be great to support ES modules without having to rewrite them into UMD first.

**Comment by jcubic** [comment]
You can't if you want to use script tag to load the file, the standard way of loading lisp file. I don't think it's possible it's not JavaScript it use fetch and eval to execute the files. So I think it's not possible. ES Modules was designed for JavaScript.

**Comment by jcubic** [comment]
I was able to create demo of using ES Module (just found old tweet where I've imported ES module in LIPS.

The demo is not working, got error:
```
TypeError: Cannot set property children of #<Element> which has only a getter
```

I think I will remove hyper app examples from the project, since hyperApp v2 have breaking changes that don't allow to use JSX like code for both React/Preact and HyperApp. It require to use hyperapp.text that is not compatible with JSX that only have single function.

**Comment by jcubic** [comment]
So Modules are supported you only need to use dynamic imports. There are defined function for dynamic import but you can easily create i with eval, I don't want to define the function because there is already import in R7RS so there would be conflict, I will leave this to the user.
