### ISSUE TITLE
security issues with browser-user scripting

### ISSUE THREAD

**Issue by waldenn** [jcubic/lips#216]
Hi, 

I was wondering if any of the potential security issues, when allowing the website user to write and execute Lips code _could_ be mitigated?

I would like the users of my website (which does not store any personal data itself) to be able to write custom Lips code and execute it. Technically a lot is possible I think (install a service worker after a browser prompt), send user data to another site, ... Just pondering how to best approach this and keep users safe.

Thanks!

**Comment by jcubic** [comment]
Do you save user data? I'm not 100% sure, but I think that if you have code written by users and executed by users you don't need to worry about anything, because it's their browser that they modify the same as with bookmarklets, user script, and extension. But if you save data from users and show it other users you can do what CodePen is doing they added CSP (Content Security Policy) for protection and make the code execute in the sandbox. I'm not sure if this is possible with LIPS because the code will be evaluated by LISP eval.

If I was you I would ask on the StackExchange site [Information Security](https://security.stackexchange.com/) what are the possible security risks. I think while you bring this up I would ask about Code playgrounds like CodePen and what are security risks.

**Comment by waldenn** [comment]
Ok. I only save some cookie data and bookmarks, nothing else. I'll dig some into the CSP options, and perhaps post the same question to SO. Thanks!
