### ISSUE TITLE
The null and undefined should be added to false values

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#330]
Accord to Scheme spec `#f` should be the only falsy value, but LIPS use two constants from JavaScript : `null` and `udefined`. I was caught multiple times when using `String::match` when I didn't use: `(not (null? x))`.

This will simplify user code if both `null` and `undefined` are false values. So the old behavior will be restored.

It's kind of silly that `null` and `undefined` are `true`.

It's intuitive to write:

```scheme
(if (str.match #/foo/)
    (display "it's foo"))
```

- [x] Update if
- [x] Update and
- [x] Update or

**Comment by lassik** [comment]
Several Scheme implementations have an "unspecifed" or "void" value. It is returned by procedures where RnRS says the return value is unspecifed. JS `undefined` would be a good fit for this purpose.

The unspecified/void value is not considered false. This is intentional.

[Survey](https://docs.scheme.org/surveys/void-value/)

**Comment by lassik** [comment]
RnRS has no clear equivalent to JS `null`. Perhaps look at how Kawa handles Java's `null`.

**Comment by jcubic** [comment]
Thanks will check.

**Comment by jcubic** [comment]
Maybe I should add warning when `if`, `and`, `or` gets `null` or `undefined` as argument. Scheme forces to use `#f` as the only false value, but if users use `if` with `null` this is probably a mistake on his end. I can make a flag to disable the warnings. @lassik what you think about something like this.

**Comment by jcubic** [comment]
Kawa have `#!null` and `#!void` constants:

```
(unless #!null (display "x\n"))
;; ==> x
(when #!void (display "x\n"))
;; ==> x
```

so `null` is `false` in Kawa.

**Comment by lassik** [comment]
> Maybe I should add warning when `if`, `and`, `or` gets `null` or `undefined` as argument.

That might be a good idea.

> `null` is `false` in Kawa.

That probably makes sense,  because `null` has a  similar purpose in Java (and JavaScript) as `#f` has in Scheme. Both `null` and `#f` are used to indicate "it would be meaningful to have an object here, but we don't have one now". This is similar to `nil` in Lisp. (As you say, Scheme does not use `nil`.)

In Scheme, `undefined` and `void` indicate "it would be meaningless to have an object here".

**Comment by lassik** [comment]
For example, `assoc` returns `#f` to indicate "I tried to find an object, but I didn't find one".

But `write` returns unspecified because it would be meaningless to return anything.
