### ISSUE TITLE
Symbol reader should terminate at single quote

### ISSUE THREAD

**Issue by aneilbaboo** [jcubic/lips#59]
Evaluating ```'a'``` produces the symbol ```a'```. I think the regex in the tokenizer needs to be updated to exclude certain characters from symbols.

**Comment by jcubic** [comment]
This is the same behavior as guile
kawa fail to parse this: `(display 'a')`
and Gauche show just a. I need to look at the R7RS spec what should be the output of this.

**Comment by jcubic** [comment]
This is the output of the parser:

```scheme
lips> (. (lips.parse "(display 'x')") 0)
(display (quote x) (quote))
```
it don't fail to parse like some Scheme implementations but this seems to work correctly.

**Comment by jcubic** [comment]
I've asked about this in r/scheme sub reddit [Parsing symbol with quote at the end or inside](https://www.reddit.com/r/scheme/comments/i618pj/parsing_symbol_with_quote_at_the_end_or_inside/)

And it seems that according to R7RS spec this behavior would be fine because the implementer decide if symbols should be extended to `'`. I think that I will revert that change since it looks better to me to allow users to create `f'` then to throw an error.

**Comment by jcubic** [comment]
If you think that this is wrong, before I've reverted the change I've asked on Reddit. Here is [whole discussion](https://www.reddit.com/r/scheme/comments/i618pj/parsing_symbol_with_quote_at_the_end_or_inside/), the best answer so far noted that in R7RS is depend on implementation to decide how it should part it. I'm fine with this.
